services:
  bot:
    build: .
    restart: always
    environment:
      - TG_API_KEY=${TG_API_KEY}
      - OUTLINE_API_URL=${OUTLINE_API_URL}
      - ADMIN_IDS=${ADMIN_IDS}
      - PROVIDER_TOKEN=${PROVIDER_TOKEN}
    volumes:
      - ./data:/app/data
